#include "stm32f.h"
#include "delay.h"
#include "glcd/glcd.h"

/*
  pb4  dc
  pb5  res
  pb6  cs

  pb13 clk
  pb15 sdin

 */

#define DCPIN 4
#define RSTPIN 5
#define CSPIN 6
#define SDCLKPIN 13
#define SDINPIN 15

#define DC(x)					x ? (gpio_set(GPIOB_BASE, 1 << DCPIN)) : (gpio_reset(GPIOB_BASE, 1 << DCPIN));
#define CS(x)					x ? (gpio_set(GPIOB_BASE, 1 << CSPIN)) : (gpio_reset(GPIOB_BASE, 1 << CSPIN));
#define SCLK(x)				x ? (gpio_set(GPIOB_BASE, 1 << SDCLKPIN)) : (gpio_reset(GPIOB_BASE, 1 << SDCLKPIN));
#define SDIN(x)				x ? (gpio_set(GPIOB_BASE, 1 << SDINPIN)) : (gpio_reset(GPIOB_BASE, 1 << SDINPIN));
#define RST(x)					x ? (gpio_set(GPIOB_BASE, 1 << RSTPIN)) : (gpio_reset(GPIOB_BASE, 1 << RSTPIN));

uint8_t frame_buffer[48 * 84 / 8];

static void send(uint8_t byte) {
  int8_t i;
  SCLK(1);
  for (i=7; i>=0; i--) {
    SCLK(0);
    SDIN(byte & (1 << i));
    SCLK(1);
  }
}

/**
 * @brief  Writes command to the LCD
 * @param LCD_Reg: address of the selected register.
 * @arg LCD_RegValue: value to write to the selected register.
 * @retval : None
 */
void oled_cmd(uint8_t reg) {
  CS(1);
  DC(0);
  CS(0);
  send(reg);
  CS(1);
}

void oled_data(uint8_t data) {
  CS(1);
  DC(1);
  CS(0);
  send(data);
  CS(1);
}

void glcd_set_contrast(uint8_t val) {
	oled_cmd(PCD8544_FUNCTION_SET | PCD8544_EXTENDED_INSTRUCTION);
	oled_cmd(PCD8544_SET_VOP | (val&0x7f));
	oled_cmd(PCD8544_FUNCTION_SET);
	oled_cmd(PCD8544_DISPLAY_CONTROL | PCD8544_DISPLAY_NORMAL);
}

void glcd_power_down(void) {
	/* First, fill RAM with zeroes to ensure minimum specified current consumption */
	glcd_clear();

	/* Power down */
	oled_cmd(PCD8544_FUNCTION_SET|PCD8544_POWER_DOWN);
}
void glcd_power_up(void) {
	oled_cmd(PCD8544_FUNCTION_SET);
}

void glcd_set_y_address(uint8_t y) {
	oled_cmd(PCD8544_SET_Y_ADDRESS|(y > 5 ? 5 : y));
}

void glcd_set_x_address(uint8_t x) {
	oled_cmd(PCD8544_SET_X_ADDRESS|(x & 0x7f));
}

void glcd_write() {
	uint8_t bank;

	for (bank = 0; bank < PCD8544_MAX_BANKS; bank++) {
		/* Each bank is a single row 8 bits tall */
		uint8_t column;

		if (glcd_bbox_selected->y_min >= (bank+1)*8) {
			continue; /* Skip the entire bank */
		}

		if (glcd_bbox_selected->y_max < bank*8) {
			break;    /* No more banks need updating */
		}

		oled_cmd(PCD8544_SET_Y_ADDRESS | bank);
		oled_cmd(PCD8544_SET_X_ADDRESS | glcd_bbox_selected->x_min);

		for (column = glcd_bbox_selected->x_min; column <= glcd_bbox_selected->x_max; column++)
		{
			oled_data( glcd_buffer_selected[PCD8544_MAX_COLS * bank + column] );
		}
	}

	glcd_reset_bbox();

}

void glcd_reset(void) {
  /* Toggle RST low to reset. Minimum pulse 100ns on datasheet. */
  //GLCD_SELECT();
  CS(0);
  //GLCD_RESET_LOW();
  RST(0);

  //delay_ms(GLCD_RESET_TIME);
  mDelay(GLCD_RESET_TIME);
  //DelayTask(GLCD_RESET_TIME);
  //GLCD_RESET_HIGH();
  RST(1);
  //GLCD_DESELECT();
  CS(1);
}

void glcd_PCD8544_init(void) {

	glcd_reset();

	/* Get into the EXTENDED mode! */
	oled_cmd(PCD8544_FUNCTION_SET | PCD8544_EXTENDED_INSTRUCTION);

	/* LCD bias select (4 is optimal?) */
	oled_cmd(PCD8544_SET_BIAS | 0x2);

	/* Set VOP (affects contrast) */
	oled_cmd(PCD8544_SET_VOP | 80); /* Experimentally determined, play with this figure until contrast looks nice */

	/* Back to standard instructions */
	oled_cmd(PCD8544_FUNCTION_SET);

	/* Normal mode */
	oled_cmd(PCD8544_DISPLAY_CONTROL | PCD8544_DISPLAY_NORMAL);
}

void oled_init(void) {      //Generated by Internal DC/DC Circuit // VCC externally supplied
  GPIO_Regs *greg;

  /* Enable GPIOD clock */
  MMIO32(RCC_AHB1ENR) |= RCC_AHB1Periph_GPIOB;

  greg = (GPIO_Regs *) GPIOB_BASE;
  greg->MODER  &= (unsigned int) ~((3 << (4 << 1))  |
                                   (3 << (5 << 1))  |
                                   (3 << (6 << 1))  |
                                   (3 << (13 << 1))  |
                                   (3 << (15 << 1))
                                   );
  greg->PUPDR  &= (unsigned int) ~((3 << (4 << 1))  |
                                   (3 << (5 << 1))  |
                                   (3 << (6 << 1))  |
                                   (3 << (13 << 1))  |
                                   (3 << (15 << 1))
                                   );
  greg->MODER |=   ((GPIO_Mode_OUT << (4 << 1))  |
                    (GPIO_Mode_OUT << (5 << 1))  |
                    (GPIO_Mode_OUT << (6 << 1))  |
                    (GPIO_Mode_OUT << (13 << 1))  |
                    (GPIO_Mode_OUT << (15 << 1))
                    );
  greg->PUPDR |= ((GPIO_PuPd_UP << (4 << 1)) |
                  (GPIO_PuPd_UP << (5 << 1)) |
                  (GPIO_PuPd_UP << (6 << 1)) |
                  (GPIO_PuPd_UP << (13 << 1)) |
                  (GPIO_PuPd_UP << (15 << 1))
                  );
  greg->OSPEEDR |= ((GPIO_Speed_100MHz << (4 << 1))  |
                    (GPIO_Speed_100MHz << (5 << 1))  |
                    (GPIO_Speed_100MHz << (6 << 1))  |
                    (GPIO_Speed_100MHz << (13 << 1))  |
                    (GPIO_Speed_100MHz << (15 << 1))
                    );
  glcd_PCD8544_init();
  glcd_clear();
}

#include "glcd/fonts/font5x7.h"
#include "glcd/fonts/Liberation_Sans15x21_Numbers.h"

void test(void) {
  oled_init();
  while(1);
}
